#!/bin/sh
# USAGE: imessage-search -C 2 cosmo
# VERSION: 0.7

sqlite3 $HOME/Library/Messages/chat.db "
  select
    datetime(date/1e9 + strftime('%s', '2001-01-01'), 'unixepoch', 'localtime'),
    chat.display_name,
    case when is_from_me then '$USER' else coalesce(handle.id, account) end,
    replace(text,  X'0A', ' · ')
  from
    message
    left outer join handle on (
      message.handle_id = handle.rowid
    ) left outer join chat_message_join on (
      message.rowid = chat_message_join.message_id
    ) left outer join chat on (
      chat.rowid = chat_message_join.chat_id
    )

" | grep "$@"
